version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: quiz
    build:
      context: ./quiz
      dockerfile: Dockerfile
    hostname: quiz
    restart: always
    logging: *default-logging